CC=gcc
CFLAGS= -g -pg -Wall -O6 -mcpu=ultrasparc -mvis 
#LDFLAGS=-L/opt/SUNWmlib/lib -R/opt/SUNWmlib/lib -lmlib -lX11 -lXext -lsocket -lnsl
#LDFLAGS= 

programstream:

clean:
	rm -f programstream *.o
